### PR TITLE
Move the new refund field

### PR DESCRIPTION
**Pull request by wvega**
# Summary

This PRs moves the moves the refund reason field above WooCommerce's refund reason field and relabels the latter to `Refund description (optional)`.

## UI Changes

- Refund fields: https://cloud.skyver.ge/12ure2Jn

### Setup

Have a commerce order or follow the steps below to fake a connection:

1. Add `add_filter( 'wc_facebook_commerce_is_available', '__return_true' );`
1. Add `add_filter( 'wc_facebook_commerce_is_connected', '__return_true' );`
1. Change the `created_via` meta of an order to `facebook`
1. Add a non empty `_wc_facebook_commerce_remote_id` meta to the order

#### Manual

1. Edit the order
1. Click the Refund button
    - [x] The `Refund reason` select field shows up below the `Refund amount` field
    - [x] The `Refund description (optional)` field shows below the `Refund reason` field
    - [x] Clicking the labels focus the correct field
    - [x] The tooltips work

#### Tests

- [x] `codecept run acceptance Admin/Orders/CommerceCest.php` pass

## Before merge

- [x] I have confirmed these changes in each supported minor WooCommerce version

### CODE REVIEW

**Review by unfulvio — CHANGES_REQUESTED** [review]
sorry @wvega ~~but I am seeing the standard refund fields~~ (se note below); I double checked the order created via is facebook (or instagram) and set the meta; I have filters running

also the test doesn't work for me, the suite throws an error:

```
In Parser.php line 128:
                                                                       
  Couldn't parse test '/srv/www/fb/public_html/wp-content/plugins/fac  
  ebook-for-woocommerce/tests/acceptance/Admin/Orders/CommerceCest.ph  
  p' on line 141                                                       
  syntax error, unexpected '' (T_ENCAPSED_AND_WHITESPACE), expecting   
  '-' or identifier (T_STRING) or variable (T_VARIABLE) or number (T_  
  NUM_STRING)     
```

[update] Sorry actually I am not seeing refund button nor fields at all once I set the order to IG/FB and add that meta - the order becomes uneditable regardless of status: I might be doing something wrong still?

**Comment by unfulvio** [comment]
Hey @wvega disregard the comment I sent previously (I deleted it to avoid confusion), I saw finally the field with the dropdown, but I ran into issues when I tried to use them. 

First, it was not clear to me that you had to select the `Refunded` status from the dropdown to show the button. This was a bit counterintuitive at first because I'm used to see it also for other statuses. 

Then, I tried to select a reason and add an amount to refund - as I clicked the button to process it, that's when I bunmped into these errors:

```
Uncaught TypeError: Cannot read property 'error' of undefined
E_DEPRECATED  Non-static method SkyVerge\WooCommerce\Facebook\Commerce\Orders::add_order_refund() should not be called statically - /wp-content/plugins/facebook-for-woocommerce/includes/Admin/Orders.php:392 
#11 [internal call] - SkyVerge\WooCommerce\Facebook\Admin\Orders->handle_refund(1063)
#10 /wp-includes/class-wp-hook.php:289 - call_user_func_array(Array[2], Array[1])
#9 /wp-includes/class-wp-hook.php:311 - WP_Hook->apply_filters(NULL, Array[2])
#8 /wp-includes/plugin.php:478 - WP_Hook->do_action(Array[2])
#7 /wp-content/plugins/woocommerce/includes/wc-order-functions.php:624 - do_action('woocommerce_re...', 1063, Array[7])
#6 /wp-content/plugins/woocommerce/includes/class-wc-ajax.php:1904 - wc_create_refund(Array[7])
#5 [internal call] - WC_AJAX::refund_line_items('')

...

Error  Call to a member function get_quantity() on array - /wp-content/plugins/facebook-for-woocommerce/includes/Commerce/Orders.php:635 
#12 /wp-content/plugins/facebook-for-woocommerce/includes/Admin/Orders.php:392 - SkyVerge\WooCommerce\Facebook\Commerce\Orders::add_order_refund(Automattic\WooCommerce\Admin\Overrides\OrderRefund, 'REFUND_REASON_...')
#11 [internal call] - SkyVerge\WooCommerce\Facebook\Admin\Orders->handle_refund(1063)
#10 /wp-includes/class-wp-hook.php:289 - call_user_func_array(Array[2], Array[1])
#9 /wp-includes/class-wp-hook.php:311 - WP_Hook->apply_filters(NULL, Array[2])
#8 /wp-includes/plugin.php:478 - WP_Hook->do_action(Array[2])
```

Additionally, the test doesn't run for me, the suite throws an error:

```
In Parser.php line 128:
                                                                       
  Couldn't parse test '/srv/www/fb/public_html/wp-content/plugins/fac  
  ebook-for-woocommerce/tests/acceptance/Admin/Orders/CommerceCest.ph  
  p' on line 141                                                       
  syntax error, unexpected '' (T_ENCAPSED_AND_WHITESPACE), expecting   
  '-' or identifier (T_STRING) or variable (T_VARIABLE) or number (T_  
  NUM_STRING)     
```

**Comment by wvega** [comment]
@unfulvio thank you for reviewing, and I'm sorry for all the troubles.

>Uncaught TypeError: Cannot read property 'error' of undefined

I'm not sure where is this one coming from and I don't see it on my logs.

>E_DEPRECATED  Non-static method SkyVerge\WooCommerce\Facebook\Commerce\Orders::add_order_refund() should not be called statically

Not part of this PR but I could have caught it earlier. Fixed in 5061bb5

>Error  Call to a member function get_quantity() on array - /wp-content/plugins/facebook-for-woocommerce/includes/Commerce/Orders.php:635 

This one was addressed in #1598.

>Additionally, the test doesn't run for me, the suite throws an error:

The syntax I used doesn't work on PHP 7.2 or older. If you are using one of those versions, I think I fixed in 9356f928.

You should be able to run the tests now, but `tests/acceptance/Admin/Orders/CommerceCest.php:try_saving_an_already_cancelled_order` is currently failing because somehow saving a Cancelled order changes its status to Pending payment.

**Comment by wvega** [comment]
@ChaseWiseman @adrianostanley I think this is ready to merge as well. I pushed modifications to address the issues that Fulvio found. 

We can address the failing test by [using CSS to disable the Order Status field](https://github.com/facebookincubator/facebook-for-woocommerce/blob/5bb79b1961bb05a52c65a5a4db35e7bcd3bb4649/assets/js/admin/facebook-for-woocommerce-settings-sync.js#L61-L69) in a separate small PR.

**Review by ChaseWiseman — APPROVED** [review]

**Pull request merged**
