### PR TITLE
Feature/store parameters

### PR DESCRIPTION
**Pull request by sc-ecolasurdo**
Implement the Commerce merchant settings ID and Instagram Business ID.
Update tests.
Add Commerce merchant settings ID and Instagram Business ID values to Setting spage.
Add new onboard parameters.

### CODE REVIEW

**Comment by jconroy** [comment]
I get the following error connecting

```
[11-Feb-2021 03:07:53 UTC] PHP Notice:  Undefined property: stdClass::$instagram_profiles in /Users/jconroy/Repos/facebook-for-woocommerce/includes/API/FBE/Installation/Read/Response.php on line 101
[11-Feb-2021 03:07:53 UTC] PHP Stack trace:
[11-Feb-2021 03:07:53 UTC] PHP   1. {main}() /Users/jconroy/Sites/local/index.php:0
[11-Feb-2021 03:07:53 UTC] PHP   2. require() /Users/jconroy/Sites/local/index.php:17
[11-Feb-2021 03:07:53 UTC] PHP   3. wp() /Users/jconroy/Sites/local/wp-blog-header.php:16
[11-Feb-2021 03:07:53 UTC] PHP   4. WP->main() /Users/jconroy/Sites/local/wp-includes/functions.php:1291
[11-Feb-2021 03:07:53 UTC] PHP   5. WP->parse_request() /Users/jconroy/Sites/local/wp-includes/class-wp.php:745
[11-Feb-2021 03:07:53 UTC] PHP   6. do_action_ref_array() /Users/jconroy/Sites/local/wp-includes/class-wp.php:388
[11-Feb-2021 03:07:53 UTC] PHP   7. WP_Hook->do_action() /Users/jconroy/Sites/local/wp-includes/plugin.php:551
[11-Feb-2021 03:07:53 UTC] PHP   8. WP_Hook->apply_filters() /Users/jconroy/Sites/local/wp-includes/class-wp-hook.php:311
[11-Feb-2021 03:07:53 UTC] PHP   9. WC_API->handle_api_requests() /Users/jconroy/Sites/local/wp-includes/class-wp-hook.php:287
[11-Feb-2021 03:07:53 UTC] PHP  10. do_action() /Users/jconroy/Repos/woocommerce/includes/class-wc-api.php:161
[11-Feb-2021 03:07:53 UTC] PHP  11. WP_Hook->do_action() /Users/jconroy/Sites/local/wp-includes/plugin.php:484
[11-Feb-2021 03:07:53 UTC] PHP  12. WP_Hook->apply_filters() /Users/jconroy/Sites/local/wp-includes/class-wp-hook.php:311
[11-Feb-2021 03:07:53 UTC] PHP  13. SkyVerge\WooCommerce\Facebook\Handlers\Connection->handle_connect() /Users/jconroy/Sites/local/wp-includes/class-wp-hook.php:287
[11-Feb-2021 03:07:53 UTC] PHP  14. SkyVerge\WooCommerce\Facebook\Handlers\Connection->update_installation_data() /Users/jconroy/Repos/facebook-for-woocommerce/includes/Handlers/Connection.php:278
[11-Feb-2021 03:07:53 UTC] PHP  15. SkyVerge\WooCommerce\Facebook\API\FBE\Installation\Read\Response->get_instagram_business_id() /Users/jconroy/Repos/facebook-for-woocommerce/includes/Handlers/Connection.php:227
```

---

I think the above error might be related to unticking "Instagram Shopping" checkbox ...

Screen Shot 2021-02-11 at 1 41 11 pm

The reason I untick it is because I'm unable us my business account (it is no longer eligible - it was the last time I tested - and I had the ID saved locally in December).

---

I can see the comment business manager id is saved.

**Comment by sc-ecolasurdo** [comment]
> Possibly related to unticking "Instagram Shopping" checkbox ?

Yes, it was that. It's fixed.

**Comment by jconroy** [comment]
Thanks @sc-ecolasurdo thanks fixed it 👍

**Comment by jconroy** [comment]
@maxdupenois @denniskwon 

I'm seeing the following warning..

Screen Shot 2021-02-12 at 2 18 29 pm

That's new right?

**Pull request merged**
