### PR TITLE
Update build and deploy instructions to add steps to install and configure Sake

### PR DESCRIPTION
**Pull request by wvega**
# Summary

Includes changes for the [Build & Release](https://github.com/facebookincubator/facebook-for-woocommerce/wiki/Build-&-Release) wiki page to add steps to install and configure Sake.

Also updates the example environment variables file to include the variable necessary to use `sake` to deploy new versions of the plugin.

## Details

I believe it would be good to update the **Deploy** section in https://github.com/facebookincubator/facebook-for-woocommerce/wiki/Build-&-Release#deploy with the content below. Since I don't have write access to the repo anymore, I'll leave the content as a suggestion here:

---

## Deploy

Facebook for WooCommerce uses Sake to build assets and deploy new versions. You can check the [Getting started](https://github.com/skyverge/sake/wiki/Getting-started) page for installation instructions.

### Environment configuration

Once Sake is installed, you'll have to set a value for the following environment variables. Make sure to copy `.env.dist` to `.env` and provide a value.

- `GITHUB_USERNAME`: your GitHub username
-  `GITHUB_API_KEY`: used to access the GitHub API to retrieve information about the repository and to create releases automatically. These can be [generated on the Applications settings page](https://github.com/settings/tokens/new?scopes=gist,repo,user&description=Facebook+for+WooCommerce+Deployments).
- `WP_SVN_USER`: the username of a WordPress.org user with permissions to commit changes to https://plugins.svn.wordpress.org/facebook-for-woocommerce/. Sake will ask for the password the first time that the user attempts to commit.
- `SAKE_PRE_RELEASE_PATH`: a path to a directory where the zip files generated with `sake prerelease` should be stored (e.g. `~/Projects/prereleases`)

You can also define these variables as shell environment variables in your `.bash_profile` (or `.zprofile` if you use zsh).

### Deploy via Sake

Run `composer install --no-dev` as a sanity check to confirm that your vendor directory is clean. It doesn't hurt if you want remove the `vendor` directory entirely and let Sake create it again during the deploy process.

Then, deploy the new version with:

```
npx sake deploy --deployAssets=0
```

Check the [Configuration](https://github.com/skyverge/sake/wiki/Configuration) and [CLI Options](https://github.com/skyverge/sake/wiki/CLI-options) pages to learn more about how to control Sake.

---

### Setup

1. Create a fork of the [Facebook for WooCommerce repo](https://github.com/facebookincubator/facebook-for-woocommerce/) (we'll call that one the **development** repo)
2. Create a [local SVN repository](https://github.com/skyverge/sake/wiki/Testing#create-a-local-svn-repository) to be used as the **production** repo
3. Clone the development repo in your machine
4. Run `npm install`
5. Copy `.env.dist` to `.env` and add the environment variables from this PR and appropriate values
4. Update `sake.config.js` as follows, replacing the path to the SVN repo:
    ```
    module.exports = {
      plugin: {
        id: 'facebook-for-woocommerce'
      },
      deploy: {
        type: 'wp',
        production: 'file:///path/to/repo'
      },
      framework: 'v5',
      deployAssets: false
    };
    ```
5. Commit the changes to `sake.config.js`
6. Prepare the plugin for deploy (bump the development version as in the [**Before deploy** instructions](https://github.com/facebookincubator/facebook-for-woocommerce/wiki/Build-&-Release#deploy)) and commit the changes

### Steps

7. Run `npx sake deploy` to deploy a new version of the plugin
    - [ ] The tasks are completed without errors
    - [ ] A release was created in the development repo
    - [ ] Changes were committed to the local SVN repo

### CODE REVIEW

**Comment by wvega** [comment]
@denniskwon  @maxdupenois now that you have access to Sake, the instructions above and the changes in this PR should help you configure it and use it to deploy new versions of the plugin.

Please let me know if you run into any problems.

**Comment by jconroy** [comment]
Thanks @wvega I've updated the wiki as suggested https://github.com/facebookincubator/facebook-for-woocommerce/wiki/Build-&-Release I've left the previous "Deploy" notes just in case for now

**Comment by jconroy** [comment]
Trying to deploy using the QA method I'm seeing

```
[16:37:42] $ svn co --force-interactive file:///Users/jconroy/facebook-test-svn /tmp/sake/facebook-test-svn
svn: E160006: No such revision 3
[16:37:43] 'shell:svn_checkout' errored after 564 ms
[16:37:43] Error: Command failed [exit code 1]: svn co --force-interactive file:///Users/jconroy/facebook-test-svn /tmp/sake/facebook-test-svn
    at formatError (/Users/jconroy/facebook-for-woocommerce/node_modules/gulp/node_modules/gulp-cli/lib/versioned/^4.0.0/format-error.js:21:10)
    at Gulp.<anonymous> (/Users/jconroy/facebook-for-woocommerce/node_modules/gulp/node_modules/gulp-cli/lib/versioned/^4.0.0/log/events.js:33:15)
    at Gulp.emit (events.js:327:22)
    at Gulp.EventEmitter.emit (domain.js:485:12)
    at Object.error (/Users/jconroy/facebook-for-woocommerce/node_modules/undertaker/lib/helpers/createExtensions.js:61:10)
    at handler (/Users/jconroy/facebook-for-woocommerce/node_modules/now-and-later/lib/mapSeries.js:47:14)
    at f (/Users/jconroy/facebook-for-woocommerce/node_modules/once/once.js:25:25)
    at f (/Users/jconroy/facebook-for-woocommerce/node_modules/once/once.js:25:25)
    at tryCatch (/Users/jconroy/facebook-for-woocommerce/node_modules/async-done/index.js:24:15)
    at done (/Users/jconroy/facebook-for-woocommerce/node_modules/async-done/index.js:40:12)
    at /Users/jconroy/facebook-for-woocommerce/node_modules/sake/tasks/shell.js:20:41
    at /Users/jconroy/facebook-for-woocommerce/node_modules/shelljs/src/exec.js:127:9
    at ChildProcess.exithandler (child_process.js:310:5)
    at ChildProcess.emit (events.js:315:20)
    at ChildProcess.EventEmitter.emit (domain.js:547:15)
    at maybeClose (internal/child_process.js:1026:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
 ```

**Comment by jconroy** [comment]
> Trying to deploy using the QA method I'm seeing

Ok got it to work. I had to manually remove the `/tmp/sake/facebook-test-svn` directory after an initial attempt failed

**Comment by jconroy** [comment]
We've had 2 team members successfully get through the QA steps. The next test will be a real deploy. Merging into the release branch as suggested by @wvega

**Pull request merged**
