### PR TITLE
Fix varSyncEnabled for product variations with removed categories

### PR DESCRIPTION
**Pull request by adrianostanley**
# Summary

This PR will fix an issue with product variations and excluded categories from syncing.

If you had a product with a few variations and **Facebook sync = Do not sync** in all of them, the product update could be blocked if its category was marked as excluded from syncing.

### Setup

1. Create a product with two or more variations
2. Give each variation a price and set **Facebook sync** to **Do not sync**
3. Associate this product with a category

### Steps

1. Go to WooCommerce > Facebook
2. Click on the Product sync tab
3. Exclude the category you used in the setup process
4. Go back to the product admin page (make sure it's refreshed after excluding its category from sync)
5. Click on the Update button
    - [x] The product is updated
6. Pick a variation and set its **Facebook sync** to **Sync and show in catalog**
7. Click on the Update button
    - [x] The modal below is shown

image

## Before merge

- [x] I have confirmed these changes in each supported minor WooCommerce version

### CODE REVIEW

**Review by unfulvio — APPROVED** [review]
hey @adrianostanley this looks good - I did not merge this yet though: are you sure it should go in #1618 feature release? can't it go in #1623 fix release? Furthermore this PR seems to be branched off from 2.0.2 (I might be wrong though) rather than 2.0.3.

**Comment by adrianostanley** [comment]
> hey @adrianostanley this looks good - I did not merge this yet though: are you sure it should go in #1618 feature release? can't it go in #1623 fix release? Furthermore this PR seems to be branched off from 2.0.2 (I might be wrong though) rather than 2.0.3.

@unfulvio yeah, correct. I just replied Will's comment [here](https://app.clubhouse.io/skyverge/story/64218/variable-products-can-not-be-updated-if-category-exclusion-applied-6#activity-65580) which is related to your review. Thanks! I'll set this PR as a draft and try to adapt it to be released.

Regarding your question about the branch, I had to branch it from `release-2.1.0` which is the one that has the `isSyncEnabledForVariableProduct()`.

**Comment by adrianostanley** [comment]
This PR will be handled by #1631.

**Comment by adrianostanley** [comment]
> > hey @adrianostanley this looks good - I did not merge this yet though: are you sure it should go in #1618 feature release? can't it go in #1623 fix release? Furthermore this PR seems to be branched off from 2.0.2 (I might be wrong though) rather than 2.0.3.
> 
> @unfulvio yeah, correct. I just replied Will's comment [here](https://app.clubhouse.io/skyverge/story/64218/variable-products-can-not-be-updated-if-category-exclusion-applied-6#activity-65580) which is related to your review. Thanks! I'll set this PR as a draft and try to adapt it to be released.
> 
> Regarding your question about the branch, I had to branch it from `release-2.1.0` which is the one that has the `isSyncEnabledForVariableProduct()`.

@unfulvio it should be well versioned in #1631.

**Pull request closed without merging**
