### PR TITLE
Implement the Commerce settings rendering

### PR DESCRIPTION
**Pull request by wvega**
# Summary

Renders the Commerce settings screen as described in the pitch.

## UI Changes

- A notice is shown if the plugin is not connected: https://cloud.skyver.ge/YEuo9Q5p
- A notice is shown if Commerce is not available: https://cloud.skyver.ge/E0un19GE
- A message is shown to indicate whether the store is connected to Commerce: https://cloud.skyver.ge/bLuRngeB and https://cloud.skyver.ge/geuzN4ve
- A Connect button is shown if the store is not connected: https://cloud.skyver.ge/bLuRngeB

### Steps

1. Add `add_filter( 'wc_facebook_connection_access_token', '__return_false' )` 
1. Go to WooCommerce > Facebook > Instagram Checkout 
    - [x] The plugin not connected message is shown
1. Remove the previous filter and add `add_filter( 'wc_facebook_commerce_is_available', '__return_false' )` 
1. Go to WooCommerce > Facebook > Instagram Checkout 
    - [x] A notice indicates that Commerce is not available
1. Remove the previous filter and add `add_filter( 'wc_facebook_commerce_is_connected', '__return_false' )`
1. Go to WooCommerce > Facebook > Instagram Checkout 
    - [x] A message indicates that the store is not connected
    - [x] A Connect button shows up
    - [x] No Save changes button is shown
1. Remove the previous filter and add `add_filter( 'wc_facebook_commerce_is_connected', '__return_true' )`
1. Go to WooCommerce > Facebook > Instagram Checkout 
    - [x] A message indicates that the store IS connected
    - [x] The Connect button does not show up
    - [x] The Save changes button is shown

### Tests

- [ ] `acceptance Admin/Settings/CommerceCest.php` tests pass

## Before merge

- [ ] I have confirmed these changes in each supported minor WooCommerce version

### CODE REVIEW

**Comment by deivamagalhaes** [comment]
It seems unrelated, but I got this error when testing the Commerce not connected step:
```
( ! ) Error: Undefined class constant 'ACTION_CONNECT_COMMERCE' in /user/Code/facebook-for-woocommerce/includes/Admin/Settings_Screens/Commerce.php on line 157
```
We may need an additional if somewhere.

**Review by deivamagalhaes — COMMENTED** [review]
The line seems unrelated to the changes in this PR, but I got this error when testing the Commerce not connected step:
```
( ! ) Error: Undefined class constant 'ACTION_CONNECT_COMMERCE' in /user/Code/facebook-for-woocommerce/includes/Admin/Settings_Screens/Commerce.php on line 157
```
We may need an additional if somewhere.

**Comment by wvega** [comment]
@deivamagalhaes that's a weird one, because the constant used on that line is [defined](https://github.com/facebookincubator/facebook-for-woocommerce/blob/8c2e0b65e2a50e2cc80470fa39a1f326382514b2/includes/Handlers/Connection.php#L41) on this branch (by the changes in #1546).

Do you mean the plugin breaks when you attempt QA steps 5 and 6?

**Comment by deivamagalhaes** [comment]
@wvega, it did break, but for some reason I don't see the error today. My PHP was probably caching something it shouldn't.

I'll continue the QA.

**Comment by deivamagalhaes** [comment]
Meanwhile, can you please check the conflicts?

**Comment by wvega** [comment]
@deivamagalhaes thanks for checking again. I merged the changes from the release branch a moment ago to fix the conflicts.

**Comment by deivamagalhaes** [comment]
@wvega , the code and the manual QA check out for me. I'm having problems running any acceptance tests though. Do you want to see if tests are still passing for you after the merge and go ahead with it, or should I add the team as reviewers so someone else can take a look?

**Comment by wvega** [comment]
@deivamagalhaes the acceptance are passing for me after the conflicts were fixed. I think we can go ahead and merge. Thank you for doing the manual QA 😁

**Review by deivamagalhaes — APPROVED** [review]

**Pull request merged**
